### ISSUE TITLE
0x2170ed0880ac9a755fd29b2688956bd959f933f8

### ISSUE THREAD

**Issue by THU2447** [bnb-chain/whitepaper#104]

**Comment by Ione90725** [comment]
what does this mean

**Comment by Mizanur1988** [comment]
![share_2023-08-16_10_24_25_796.jpeg_2023-08-16_10_24_25.jpg](https://github.com/bnb-chain/whitepaper/assets/123995787/75038b9d-2dd6-43cc-8f4d-814790045347)
