### ISSUE TITLE
Read Only wallet open file installing! Account Privet key into Trust wallet account 0xdfd5293d8e347dfe59e90efd55b2956a1343963d 1inch Ethereum Wallet

### ISSUE THREAD

**Issue by THU2447** [bnb-chain/whitepaper#116]
Read Only wallet open file installing! Account Privet key into Trust wallet account 0xdfd5293d8e347dfe59e90efd55b2956a1343963d 1inch Ethereum Wallet

_Originally posted by @THU2447 in https://github.com/bnb-chain/whitepaper/issues/31#issuecomment-1579224736_

**Comment by Mizanur1988** [comment]
![share_2023-08-16_10_24_25_796.jpeg_2023-08-16_10_24_25.jpg](https://github.com/bnb-chain/whitepaper/assets/123995787/6dff53c8-d730-4903-8dda-cc94b02d6cad)
