### ISSUE TITLE
I would like to known what's Websocket Address of BNBChain

### ISSUE THREAD

**Issue by havoanhnguyen** [bnb-chain/whitepaper#150]
Hi all, this is not an issue, I wanna know Websocket to subscribe balance of the wallet address.
For example, I would like to know address is 0xFB765Ad1f2D9dcaA761c3bA0e7946FA1e63d0B70 has a transaction and the balance change. (from, to, number, gas free ...), or how to detect it without calling HTTP API interval (because it not real-time).
tks for your help.

**Comment by deepcrazy** [comment]
You can refer this guide probably: https://docs.alchemy.com/reference/best-practices-for-using-websockets-in-web3
In addition to this, here is the list of RPC endpoints: https://docs.bnbchain.org/docs/rpc. It is generally recommended to use third party rpc which can be referred here: https://docs.bnbchain.org/docs/rpc#thrid-party-rpc-providers. As an eg: you can use this one: https://www.ankr.com/rpc/bsc

**Comment by havoanhnguyen** [comment]
yeah. Thank you, I found the solution for my case. I work with Chainstack, based on your suggestion, Tks @deepcrazy very much.
