### ISSUE TITLE
BNB智能链.md

### ISSUE THREAD

**Issue by 072222** [bnb-chain/whitepaper#191]
BNB智能链.md

**Comment by shango420** [comment]
> BNB智能链.md

- [ ] ![2023-06-30_Estado de cuenta.pdf](https://github.com/bnb-chain/whitepaper/files/13171962/2023-06-30_Estado.de.cuenta.pdf)

[]()[]()Dhttps://api-m.paypal.com/v2/checkout/orders/5O190127TN364715T

**Comment by shango420** [comment]
https://api-m.paypal.com/v2/checkout/orders/5O190127TN364715T
