### ISSUE TITLE
token 

### ISSUE THREAD

**Issue by lyn4935** [bnb-chain/whitepaper#208]
确保在两条链上的 BEP2 代币和 BEP2E代币具有相同的总供应量。与更典型的ERC20合约 相比，BEP2E必须添加以下有3 种函数：
symbol()： 获取代币符号
decimals()： 获取代币十进制小数位数
getOwner()： 获取绑定合约所有者的地址。这个值应该在 BEP2E合约构造函数中初始化，以便绑定操作可以进一步验证绑定消息是否得到来自 BEP2E的发行者。[](url)

**Comment by lyn4935** [comment]
https://github.com/bnb-chain/whitepaper/issues/208#issue-2027883100

**Comment by qwe5926345** [comment]
https://github.com/bnb-chain/whitepaper/issues/826039752#209
