### ISSUE TITLE
Make "walleting transfers" less complicated

### ISSUE THREAD

**Issue by Copper111867** [bnb-chain/whitepaper#31]
It would just be great to open your cyberwaet just as easy it is opening your wallet or purse in real life. :)

**Comment by andreza305** [comment]
Se realmente eu ganhar dinheiro de verdade eu vou indicar para os meus amigos

**Comment by THU2447** [comment]
Read Only wallet open file installing! Account Privet key into Trust wallet account 0xdfd5293d8e347dfe59e90efd55b2956a1343963d 1inch Ethereum Wallet
