### ISSUE TITLE
BSC🎉✨

### ISSUE THREAD

**Issue by mark-ify** [bnb-chain/whitepaper#35]
Great move... With the appreciation of new blockchain mechanism. Such a beautiful process.

**Comment by Avinash735** [comment]
> Great move... With the appreciation of new blockchain mechanism. Such a beautiful process.

Good

**Comment by Avinash735** [comment]
> Great move... With the appreciation of new blockchain mechanism. Such a beautiful process.

Good

**Comment by royalinouman555** [comment]
Great move.

**Comment by krairat12** [comment]
👍

**Comment by MHadi68** [comment]
Tnx 👌❤️

**Comment by Robertoataop** [comment]
> beautiful
